version: '1'

services:
  db:
    image: 'postgres:15.2-alpine'
    restart: always
    environment:
        POSTGRES_DB: postgres
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    expose:
      - "5432"
    networks:
      - backend
  app:
    build: .
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"
    networks:
      - backend
    environment:
      - REDIS_ADDR=redis:6379
      - REDIS_PASSWORD=redis
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - DB_SSL=disable
  redis:
    image: 'redis:6.2-alpine'
    restart: always
    ports:
      - "6379:6379"
    expose:
      - "6379"
    networks:
      - backend
networks:
  backend:
    driver: bridge